# Generated by Django 5.0.1 on 2026-06-30 05:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de Turno')),
                ('user_id', models.CharField(db_index=True, max_length=50, verbose_name='ID del Usuario')),
                ('user_name', models.CharField(max_length=200, verbose_name='Nombre del Usuario')),
                ('user_role', models.CharField(blank=True, max_length=50, verbose_name='Rol del Usuario')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=20, verbose_name='Estado')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Inicial')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Efectivo Final')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Recaudado')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Efectivo')),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Tarjeta')),
                ('total_transfer_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Transferencia')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Total Transacciones')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia en Caja')),
                ('opening_notes', models.TextField(blank=True, verbose_name='Notas de Apertura')),
                ('closing_notes', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-opened_at'],
            },
        ),
    ]
