# Generated by Django 5.0.1 on 2026-06-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-opened_at', '-scheduled_start'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='shift',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Programado'),
        ),
        migrations.AddField(
            model_name='shift',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Programado'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='opened_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Apertura'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('open', 'Abierto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=20, verbose_name='Estado'),
        ),
    ]
