# Generated by Django 5.0.1 on 2026-03-07 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_number', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Número de Reservación')),
                ('guest_name', models.CharField(max_length=150, verbose_name='Nombre del invitado')),
                ('guest_phone', models.CharField(max_length=25, verbose_name='Teléfono del invitado')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del invitado')),
                ('party_size', models.PositiveIntegerField(default=1, verbose_name='Número de personas')),
                ('reservation_date', models.DateField(verbose_name='Fecha de la reserva')),
                ('reservation_time', models.TimeField(verbose_name='Hora de la reserva')),
                ('duration_minutes', models.PositiveIntegerField(default=90, help_text='Duración estimada de la visita', verbose_name='Duración (minutos)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('seated', 'En Mesa'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('special_requests', models.TextField(blank=True, help_text='Alergias, preferencias, necesidades especiales', verbose_name='Solicitudes especiales')),
                ('occasion', models.CharField(choices=[('none', 'Sin ocasión especial'), ('birthday', 'Cumpleaños'), ('anniversary', 'Aniversario'), ('business', 'Reunión de negocios'), ('graduation', 'Graduación'), ('other', 'Otro')], default='none', max_length=20, verbose_name='Ocasión')),
                ('created_by_id', models.CharField(blank=True, max_length=50, verbose_name='ID del usuario que creó')),
                ('created_by_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del usuario que creó')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el')),
                ('seated_at', models.DateTimeField(blank=True, null=True, verbose_name='Sentado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado el')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='customers.customer', verbose_name='Cliente')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pos.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_by', models.CharField(blank=True, max_length=200, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reservations.reservation', verbose_name='Reservación')),
            ],
            options={
                'verbose_name': 'Nota de Reservación',
                'verbose_name_plural': 'Notas de Reservaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_number'], name='reservation_reserva_3144d8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_date', 'status'], name='reservation_reserva_4f8570_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest_phone'], name='reservation_guest_p_668570_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table', 'reservation_date'], name='reservation_table_i_b9bc23_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'reservation_date'], name='reservation_status_f2b721_idx'),
        ),
    ]
