# Generated by Django 5.0.1 on 2026-03-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='cash_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Pagos en Efectivo'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='cop_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Pagos en COP'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='cop_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas en COP'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='transfer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Pagos por Transferencia'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='transfer_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas por Transferencia'),
        ),
    ]
