# Generated by Django 5.0.1 on 2026-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='role',
            field=models.CharField(choices=[('pos', 'Punto de Venta (POS)'), ('kitchen', 'Cocina'), ('fortaleza', 'Fortaleza'), ('both', 'Ambas funciones')], default='pos', help_text='pos = solo tickets de venta | kitchen = solo órdenes de cocina | both = ambas funciones', max_length=10, verbose_name='Rol de Impresora'),
        ),
    ]
