# Generated by Django 5.0.1 on 2026-05-30 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRIConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vsr_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token VSR / FactuExpress')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuraciones SRI',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='sri_access_key',
            field=models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de Acceso SRI'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sri_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Factura SRI'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sri_status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('QUEUED', 'En Cola'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20, verbose_name='Estado SRI'),
        ),
    ]
