# Generated by Django 5.0.1 on 2026-05-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_sriconfiguration_payment_sri_access_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sriconfiguration',
            name='vsr_token',
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='emission_point',
            field=models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='encrypted_vsr_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token VSR Encriptado'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='environment',
            field=models.CharField(choices=[('TEST', 'Pruebas / Test'), ('PRODUCTION', 'Producción')], default='TEST', max_length=20, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='establishment_code',
            field=models.CharField(default='001', max_length=3, verbose_name='Código de Establecimiento'),
        ),
        migrations.AlterField(
            model_name='sriconfiguration',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='¿Activo?'),
        ),
    ]
