# Generated by Django 5.0.1 on 2026-05-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Piso')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Habitación')),
                ('room_type', models.CharField(choices=[('single', 'Simple'), ('double', 'Doble'), ('suite', 'Suite'), ('matrimonial', 'Matrimonial')], default='single', max_length=20, verbose_name='Tipo de Habitación')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Noche')),
                ('adult_capacity', models.PositiveIntegerField(default=2, verbose_name='Capacidad de Adultos')),
                ('child_capacity', models.PositiveIntegerField(default=0, verbose_name='Capacidad de Niños')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('cleaning', 'Limpieza'), ('maintenance', 'Mantenimiento')], default='available', max_length=20, verbose_name='Estado')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.floor', verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['room_number'],
            },
        ),
    ]
