# Generated by Django 5.0.1 on 2026-06-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Individual'), ('double', 'Doble'), ('matrimonial', 'Matrimonial'), ('familiar', 'Familiar')], default='single', max_length=20, verbose_name='Tipo de Habitación'),
        ),
    ]
