# Generated by Django 5.0.1 on 2026-06-30 06:32

import django.db.models.deletion
from django.db import migrations, models


def populate_and_convert_room_types(apps, schema_editor):
    RoomType = apps.get_model('rooms', 'RoomType')
    Room = apps.get_model('rooms', 'Room')
    
    # Create default room types
    rt_single, _ = RoomType.objects.get_or_create(
        name='Individual',
        defaults={'price_per_adult': 15.00, 'price_per_child': 8.00, 'adult_capacity': 1, 'child_capacity': 1}
    )
    rt_double, _ = RoomType.objects.get_or_create(
        name='Doble',
        defaults={'price_per_adult': 15.00, 'price_per_child': 8.00, 'adult_capacity': 2, 'child_capacity': 2}
    )
    rt_matrimonial, _ = RoomType.objects.get_or_create(
        name='Matrimonial',
        defaults={'price_per_adult': 15.00, 'price_per_child': 8.00, 'adult_capacity': 2, 'child_capacity': 2}
    )
    rt_familiar, _ = RoomType.objects.get_or_create(
        name='Familiar',
        defaults={'price_per_adult': 15.00, 'price_per_child': 8.00, 'adult_capacity': 3, 'child_capacity': 2}
    )
    
    # Convert existing string values to room type IDs (stored as text in room_type field)
    for room in Room.objects.all():
        old_type = room.room_type.lower()
        if old_type == 'single' or 'indiv' in old_type:
            room.room_type = str(rt_single.id)
        elif old_type == 'double' or 'doble' in old_type:
            room.room_type = str(rt_double.id)
        elif old_type == 'matrimonial' or 'matri' in old_type:
            room.room_type = str(rt_matrimonial.id)
        elif old_type == 'familiar' or 'famil' in old_type:
            room.room_type = str(rt_familiar.id)
        else:
            # Fallback
            room.room_type = str(rt_single.id)
        room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo')),
                ('price_per_adult', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='Precio por Adulto')),
                ('price_per_child', models.DecimalField(decimal_places=2, default=8.0, max_digits=10, verbose_name='Precio por Niño (>2 años)')),
                ('adult_capacity', models.PositiveIntegerField(default=2, verbose_name='Capacidad Máxima Adultos')),
                ('child_capacity', models.PositiveIntegerField(default=2, verbose_name='Capacidad Máxima Niños')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
            },
        ),
        migrations.RunPython(populate_and_convert_room_types),
        migrations.RemoveField(
            model_name='room',
            name='adult_capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='child_capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='Tipo de Habitación'),
        ),
    ]
