# Generated by Django 5.0.1 on 2026-05-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('encrypted_vsr_token', models.TextField(blank=True, null=True, verbose_name='Token VSR Encriptado')),
                ('environment', models.CharField(choices=[('TEST', 'Pruebas / Test'), ('PRODUCTION', 'Producción')], default='TEST', max_length=20, verbose_name='Ambiente')),
                ('establishment_code', models.CharField(default='001', max_length=3, verbose_name='Código de Establecimiento')),
                ('emission_point', models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión')),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuraciones SRI',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(verbose_name='Fecha/Hora Check-in')),
                ('check_out_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Check-out')),
                ('number_of_adults', models.PositiveIntegerField(default=1, verbose_name='Número de Adultos')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='Número de Niños')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('checked_out', 'Completada (Check-out)'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest', verbose_name='Huésped')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Pago')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], default='cash', max_length=20, verbose_name='Método de Pago')),
                ('sri_access_key', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de Acceso SRI')),
                ('sri_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Factura SRI')),
                ('sri_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('QUEUED', 'En Cola'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20, verbose_name='Estado SRI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation', verbose_name='Reservación')),
            ],
            options={
                'verbose_name': 'Pago / Factura',
                'verbose_name_plural': 'Pagos / Facturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
