# Generated by Django 5.0.1 on 2026-06-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_hotelsettings_payment_is_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checked_in_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Check-in por'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_out_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Check-out por'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Check-out'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children_over_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños mayores de 2 años'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children_under_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños menores de 2 años'),
        ),
    ]
