# Generated by Django 5.0.1 on 2026-06-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('reservations', '0003_reservation_checked_in_by_reservation_checked_out_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reports.shift', verbose_name='Turno'),
        ),
    ]
