# Generated by Django 5.0.1 on 2026-07-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_payment_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Noche (Manual)'),
        ),
    ]
