# Generated by Django 5.0.1 on 2026-07-02 18:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de materia prima')),
                ('unit', models.CharField(help_text='Ej: Unidades, Kg, Gramos, Litros, Porciones', max_length=50, verbose_name='Unidad de medida')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Anterior')),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso')),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Consumo')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Actual')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='inventory.rawmaterial', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Inventario Diario',
                'verbose_name_plural': 'Inventarios Diarios',
                'ordering': ['-date', 'raw_material__name'],
                'unique_together': {('date', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de materia prima que se descuenta al vender 1 unidad de este producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Usada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='menu.product', verbose_name='Producto')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.rawmaterial', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Item de Receta',
                'verbose_name_plural': 'Items de Receta',
                'unique_together': {('raw_material', 'product')},
            },
        ),
    ]
