# Generated by Django 5.0.1 on 2026-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'ID Exterior')], default='05', max_length=2, verbose_name='Tipo de Identificación')),
                ('identification', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre / Razón Social')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'ordering': ['name'],
            },
        ),
    ]
