# Generated by Django 5.0.1 on 2026-06-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='guest',
            name='origin_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='De qué parte viaja'),
        ),
    ]
