# Generated by Django 5.0.1 on 2026-03-07 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Acumulado de pagos parciales', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Pagado'),
        ),
    ]
