# Generated by Django 5.0.1 on 2026-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ya pagado (separado)'),
        ),
    ]
